apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    namespace: argoapps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: 
    targetRevision: HEAD